repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/
      - id: end-of-file-fixer
        exclude: ^tests/
      - id: check-yaml
        exclude: ^tests/|^miloco_sdk/plugin/miot/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [ "--line-length=120" ]
        exclude: ^tests/|^miloco_sdk/plugin/miot/

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [ "--profile", "black", "--line-length", "120" ]
        exclude: ^tests/|^miloco_sdk/plugin/miot/

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: [
          'flake8-bugbear',
          'flake8-comprehensions',
        ]
        args: [
          "--max-line-length=120",
          "--max-complexity=20",
          "--ignore=E203,E266,E501,W503,F403,F401,E731,E711,C901,F841,D103,B008,D400,E402,E712",
          "--exclude=tests/*"
        ]
        exclude: ^tests/|^miloco_sdk/plugin/miot/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies: [ types-requests, pydantic ]
        args: [ "miloco_sdk", "--exclude", "miloco_sdk/plugin/miot/", "--exclude", "tests/", "--follow-imports=skip" ]
        pass_filenames: false
